server:
  port: 8080
  contextPath:
  upload:
    dir: /data/log/upload/

spring:
  profiles:
    active: dev

  mongodb:
    host: 127.0.0.1
    port: 27017
    database: cxszsh
    username: cxadmin
    password: cxszsh

  redis:
    host: 127.0.0.1
    port: 6379
    expiration: 604800    

logging:
  path: /tmp/log/sbs

jwt:
  secret: mySecret
  expiration: 604800
  authType: Bearer

qiniu:
  accessKey: 
  secretKey: 
  bucketName: 
  bucketHost: 
