server:
  port: 8080
  contextPath:
  machineId: 1
  upload:
    dir: /data/log/upload/

spring:
  profiles:
    active: dev

  mongodb:
    host: 127.0.0.1
    port: 27017
    database: cxszsh
    username: cxadmin
    password: cxszsh

  redis:
    host: 127.0.0.1
    port: 6379
    expiration: 604800    

logging:
  path: /tmp/log/cxszsh

jwt:
  secret: mySecret
  expiration: 604800
  authType: Bearer
  qidiAuthType: Qidi

qidi:
  auth:
    url: http://183.224.41.198:8088/nqsky-meap-front/open.jws

qiniu:
  accessKey: IZV4vlVHlVOS6lpaOD0XPL4ez5s69tforscCA_GO
  secretKey: rKN1i8N4ilLVxvZGpxLCt7JhDMA-P7W27x3xUAkW
  bucketName: cxszsh
  bucketHost: http://o86g88ag4.bkt.clouddn.com

spider:
  traffic:
    illegal:
      url: http://116.55.248.41/yntpgov/Home/CarIllegalList
      openId: oIg0Ej-0OTj6_XrouPaiw1clhxzE
      publicId: gh_11fa59771cc7
  insurance:
    url: http://wx.ynhrss.gov.cn:12337/HrssWechat/HrssWechatAction.do
    areano: 5323
